# Generated by Django 3.0.4 on 2020-03-16 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resumecategory',
            options={'verbose_name': 'Categories of resume'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service'},
        ),
        migrations.AlterModelOptions(
            name='skillcategory',
            options={'verbose_name': 'Categories of skill'},
        ),
        migrations.AddField(
            model_name='image',
            name='portfolio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='personal.Portfolio', verbose_name='Portfolio'),
        ),
        migrations.AddField(
            model_name='skill',
            name='skillCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='personal.SkillCategory', verbose_name='Skill Category'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resumeCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.ResumeCategory', verbose_name='resume category'),
        ),
    ]
