# Generated by Django 3.0.4 on 2020-03-16 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20200316_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='portfolio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='personal.Portfolio', verbose_name='Portfolio'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resumeCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='personal.ResumeCategory', verbose_name='resume category'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skillCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='personal.SkillCategory', verbose_name='Skill Category'),
        ),
    ]
