# Generated by Django 3.0.4 on 2020-03-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_auto_20200316_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='degree_en',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='degree_fi',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='degree_fr',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='description_fi',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='place_en',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='place_fi',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='place_fr',
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='name_en',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='name_fi',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='name_fr',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='name'),
        ),
    ]
