# Generated by Django 3.0.4 on 2020-03-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_auto_20200316_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='degree_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='degree_fi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='degree_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='description_fi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='place_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='place_fi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='place_fr',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
