# Generated by Django 3.0.4 on 2020-03-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_auto_20200316_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='degree_fi',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='description_fi',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='place_fi',
        ),
        migrations.RemoveField(
            model_name='resumecategory',
            name='name_fi',
        ),
        migrations.AddField(
            model_name='image',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='image',
            name='description_fr',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='image',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='image',
            name='title_fr',
            field=models.CharField(max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_fr',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='name'),
        ),
    ]
