# Generated by Django 3.0.4 on 2020-03-16 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_auto_20200316_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(null=True, verbose_name='slug'),
        ),
    ]
