# Generated by Django 3.0.4 on 2020-03-17 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0008_portfolio_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='appurl',
            field=models.URLField(null=True, verbose_name='appurl'),
        ),
    ]
