# Generated by Django 3.0.4 on 2020-03-17 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0009_image_appurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('comment', models.TextField(verbose_name='comment')),
            ],
        ),
    ]
