# Generated by Django 3.0.4 on 2020-03-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0011_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('picture', models.URLField(verbose_name='picture')),
                ('job', models.CharField(max_length=50, verbose_name='job')),
                ('comment', models.TextField(verbose_name='comment')),
            ],
        ),
    ]
