# Generated by Django 3.0.4 on 2020-03-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0012_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='comment_en',
            field=models.TextField(null=True, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='customer',
            name='comment_fr',
            field=models.TextField(null=True, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='customer',
            name='job_en',
            field=models.CharField(max_length=50, null=True, verbose_name='job'),
        ),
        migrations.AddField(
            model_name='customer',
            name='job_fr',
            field=models.CharField(max_length=50, null=True, verbose_name='job'),
        ),
        migrations.AddField(
            model_name='customer',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='customer',
            name='name_fr',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
    ]
