# Generated by Django 3.0.4 on 2020-07-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0014_certification_certificationcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='certification',
            name='description_fr',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='certification',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='certification',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='certification',
            name='school_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='school'),
        ),
        migrations.AddField(
            model_name='certification',
            name='school_fr',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='school'),
        ),
        migrations.AddField(
            model_name='certification',
            name='slug_en',
            field=models.SlugField(null=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='certification',
            name='slug_fr',
            field=models.SlugField(null=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='certificationcategory',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='certificationcategory',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='name'),
        ),
    ]
