# Generated by Django 3.0.4 on 2020-07-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0016_certificationcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='school',
            field=models.CharField(max_length=100, verbose_name='school'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='school_en',
            field=models.CharField(max_length=100, null=True, verbose_name='school'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='school_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='school'),
        ),
    ]
