# Generated by Django 3.0.4 on 2020-07-04 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0017_auto_20200704_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='picture_certification',
        ),
    ]
