# Generated by Django 3.0.4 on 2020-07-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0018_remove_certification_picture_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='picture_certification',
            field=models.URLField(null=True, verbose_name='picture_certification'),
        ),
    ]
